//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basket
    {
        public int Id { get; set; }
        public int Quantity { get; set; }
        public double Total { get; set; }
        public string UserId { get; set; }
        public int ProductId { get; set; }
        public string ProductCode { get; set; }
        public System.DateTime RecordDate { get; set; }
        public Nullable<System.DateTime> RecordDeleteDate { get; set; }
        public bool RecordIsDeleted { get; set; }
    }
}
