//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favorite
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public string ProductCode { get; set; }
        public string RecordUserId { get; set; }
        public System.DateTime RecordDate { get; set; }
        public bool RecordIsDeleted { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ProductSKU ProductSKU { get; set; }
    }
}
