//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSKU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductSKU()
        {
            this.Favorites = new HashSet<Favorite>();
            this.ProductCodeImages = new HashSet<ProductCodeImage>();
            this.ProductSizes = new HashSet<ProductSize>();
        }
    
        public string ProductCode { get; set; }
        public int ProductId { get; set; }
        public int ColorId { get; set; }
        public int ProductSizeId { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<double> MarketPrice { get; set; }
        public Nullable<double> SellPrice { get; set; }
        public bool RecordIsDeleted { get; set; }
        public System.DateTime RecordDate { get; set; }
        public string RecordUserId { get; set; }
    
        public virtual Color Color { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favorite> Favorites { get; set; }
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCodeImage> ProductCodeImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSize> ProductSizes { get; set; }
    }
}
